version: '3.1'
services:
  postgres-db:
    user: root
    image: postgres:12.3
    container_name: postgres-db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
volumes:
  postgres-data:
