version: "3.0"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8081:8080"
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ../project-under-test:/var/jenkins_home/workspace/mvn-project

volumes:
    jenkins_home:
        external: true
